AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false