default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: homie_test_development

test:
  <<: *default
  database: homie_test_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
